services:
  # 쓰기 전용 마스터 MySQL 서버
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - '3307:3306'
    networks:
      - mysql-cluster
    volumes:
      - ./init_write.sql:/docker-entrypoint-initdb.d/init.sql

  # 읽기 전용 슬레이브 MySQL 서버
  mysql-slave:
    image: mysql:latest
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - '3308:3306'
    networks:
      - mysql-cluster
    depends_on:
      - mysql-master
    volumes:
      - ./init_read.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mysql-cluster:
    driver: bridge
